language: lua
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y lua5.1 luarocks 
    - lua -v
    - luarocks --version
    - sudo luarocks install busted
    - sudo luarocks install luacheck
script:
    - luacheck tsq.lua tsw.lua
    - "busted *_test.lua"

